---
locale: en-US
title: Ankush Gupta
name: Ankush Gupta
url: https://ankushg.com
repository: ankushg/ankushg.com
email: me@ankushg.com
description: Trials and tribulations of Ankush, the Software Engineer.
twitter_username: ankushg
github_username: ankushg
minimal_mistakes_skin: default
search: true
twitter:
  username: ankushg
facebook:
  username: ankushmgupta
og_image: "/assets/images/og_image.jpg"
social:
  type: Person
  name: Ankush Gupta
  links:
  - https://ankushg.com
  - https://ankushg.com/feed.xml
  - https://twitter.com/ankushg
  - https://github.com/ankushg
  - https://www.linkedin.com/in/ankushmg/
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-1190814-10
    anonymize_ip: false
markdown: kramdown
theme: minimal-mistakes-jekyll
permalink: "/posts/:title/"
timezone: America/Los_Angeles
include:
- _pages
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll_picture_tag
author:
  name: Ankush Gupta
  avatar: "/assets/images/bio-photo.jpg"
  bio: I'm a Software Engineer at [Quizlet](https://quizlet.com).<br/><br/>I
    currently focus delivering awesome experiences with Android and Kotlin Multiplatform
    -- both for our users and my fellow engineers.
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/ankushg
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/ankushg
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/ankushmg/
  - label: Feed
    icon: fas fa-fw fa-rss-square
    url: https://ankushg.com/feed.xml
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/ankushg
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/ankushg
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/ankushmg/
defaults:
- scope:
    path: ""
  values:
    layout: single
    author_profile: true
- scope:
    path: "_posts/posts"
  values:
    permalink: "/posts/:title/"
    show_date: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: "_posts/speaking"
  values:
    show_date: true
    permalink: "/speaking/:title/"
    read_time: false
- scope:
    path: "_posts/projects"
  values:
    show_date: true
    permalink: "/projects/:title/"
    read_time: false
- scope:
    path: "_pages"
    type: "pages"
  values:
    permalink: "/:basename/"
    show_date: false
