name: Lighthouse
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.9
      - name: Set the preview url
        run: |
          sanitized_branch=$(echo ${{ steps.branch-name.outputs.current_branch }} | sed -e 's/\//-/g')
          preview_url=https://$sanitized_branch.ankushg.pages.dev
          echo "Cloudflare preview url is $preview_url"
          echo "preview_url=$preview_url" >> $GITHUB_ENV
      - name: Wait for Cloudflare Pages deploy to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Cloudflare Pages"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - name: Audit URLs using Lighthouse
        id: LHCI
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ env.preview_url }}
            ${{ env.preview_url }}/posts/
            ${{ env.preview_url }}/about/
          budgetPath: ./budget.json
          uploadArtifacts: true
          runs: 3
      - name: Add results to run check
        uses: manrueda/lighthouse-report-action@v1.1.2
        with:
          reports: ${{steps.LHCI.outputs.resultsPath}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
